### ISSUE TITLE
Anyway to disable the logs being access web-interface

### ISSUE THREAD

**Issue by projx** [OneCDOnly/RunLast#9]
Hey

QNAP being QNAP, don't provide any form of authentication for 3rd party apps, so the RunLast logs are accessible to everybody on the network - Is there anyway to prevent RunLast making them accessible via a browser?

Also awesome tools, thanks for taking the time to put this together, its solved a major headache for me using docker-compose. I can simple run 

`docker start $(docker ps -a -q)`

And everything starts!

**Comment by OneCDOnly** [comment]
Hi @projx yes, if you'd like to disable the web access to the logs, you'll need to do some hacking. I've included the commands to do this below. 

Remove the web UI entry for RunLast from the App Center config:
```
setcfg RunLast WebUI '' -f /etc/config/qpkg.conf
```
... then stop RunLast generating a symlink to the log accessible via the web UI:
```
sed -e '/GUI_LOG_PATHFILE/ s/^#*/#/' -i $(getcfg RunLast Install_Path -f /etc/config/qpkg.conf)/runlast.sh
```
... and finally, remove the existing web UI symlink:
```
rm /home/httpd/RunLast.log
```
**Note:** RunLast will still generate logs, but they will not be accessible via the web UI anymore.
